Repository phakhruddin/splunkonpremiscloud, pull requests merged in 2024-12, with the labels that each got.

#1 doc (splunk) : Update README.md
  README.md
Labels: documentation

#8 feat(splunk): create file and dirs
  .flake8
  .github/workflows/bash-ci.yml
  .github/workflows/lint.yml
  .github/workflows/python-ci.yml
  .github/workflows/release.yml
  .pre-commit-config.yaml
  Makefile
  README.md
  bash/scripts/common_functions.sh
  bash/scripts/configure_splunk_node.sh
  bash/scripts/deploy_infrastructure.sh
  bash/tests/test_configure_splunk_node.sh
  bash/tests/test_deploy_infrastructure.sh
  python/main.py
  python/splunk/__init__.py
  python/splunk/deployer.py
  python/splunk/node_manager.py
  python/splunk/utils/__init__.py
  python/splunk/utils/ec2_helper.py
  python/splunk/utils/s3_backend.py
  python/splunk/utils/yaml_loader.py
  python/tests/test_deployer.py
  python/tests/test_node_manager.py
  python/tests/test_utils/test_s3_backend.py
  python/tests/test_utils/test_yaml_loader.py
  requirements.txt
  setup.py
  splunk_deployment.yaml
Labels: enhancement

#9 doc(splunk): upd readme
  README.md
Labels: documentation

#10 doc(splunk): upd
  README.md
Labels: documentation

#12 feat(splunk): update
  .flake8
  .github/workflows/python.yml
  .github/workflows/terraform.yml
  README.md
  python/main.py
  python/scripts/setup_splunk.sh
  python/splunk/__init__.py
  python/splunk/deployer.py
  python/splunk/node_manager.py
  python/splunk/tests/test_deployer.py
  python/splunk/tests/test_node_manager.py
  python/splunk/tests/test_utils/test_splunk_api.py
  python/splunk/tests/test_utils/test_yaml_loader.py
  python/splunk/utils/__init__.py
  python/splunk/utils/ec2_manager.py
  python/splunk/utils/splunk_api.py
  python/splunk/utils/yaml_loader.py
  terraform/envs/dev/backend.tf
  terraform/envs/dev/main.tf
  terraform/envs/dev/variables.tfvars
  terraform/envs/prod/backend.tf
  terraform/envs/prod/main.tf
  terraform/envs/prod/variables.tfvars
  terraform/modules/aws/nacl/main.tf
  terraform/modules/aws/nacl/outputs.tf
  terraform/modules/aws/nacl/variables.tf
  terraform/modules/aws/vpc/main.tf
  terraform/modules/aws/vpc/outputs.tf
  terraform/modules/aws/vpc/variables.tf
  terraform/modules/splunk/main.tf
  terraform/modules/splunk/outputs.tf
  terraform/modules/splunk/variables.tf
  terraform/vpc_config.yaml
Labels: enhancement

#13 doc(splunk): update
  README.md
Labels: documentation

#14 doc(splunk): update
  README.md
Labels: documentation

#19 doc(splunk): upd
  .github/PULL_REQUEST_TEMPLATE
  .github/bug_fix_template.md
  .github/feature_request_template.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  ROADMAP.md
  SECURITY.md
Labels: documentation, help wanted, good first issue

#20 doc(splunk): feat
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#21 merge main to dev
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE
  .github/bug_fix_template.md
  .github/feature_request_template.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  ROADMAP.md
  SECURITY.md
Labels: documentation

#25 fix codecov
  README.md
Labels: bug

#28 feat(splunk): upd python.yml CICD
  .github/workflows/python.yml
  requirements.txt
Labels: enhancement

#29 Fix Badge
  README.md
Labels: bug, enhancement, help wanted

#33 feat(splunk): update outputs.tf
  terraform/modules/splunk/outputs.tf
Labels: enhancement

#34 feat(splunk): Update env main.tf
  terraform/envs/dev/main.tf
Labels: enhancement

#35 feat(splunk): Update backend.tf
  terraform/envs/dev/backend.tf
Labels: enhancement

#36 merge main to deenupdate
  .flake8
  .github/workflows/python.yml
  .github/workflows/terraform.yml
  Dockerfile
  README.md
  requirements.txt
  terraform/envs/dev/backend.tf
  terraform/envs/dev/main.tf
  terraform/modules/splunk/main.tf
  terraform/modules/splunk/outputs.tf
  terraform/modules/splunk/variables.tf
Labels: help wanted

#38 merge main to development
  .github/workflows/python.yml
  core/bash/scripts/common_functions.sh
  core/bash/scripts/configure_splunk_node.sh
  core/bash/scripts/deploy_infrastructure.sh
  core/bash/tests/test_configure_splunk_node.sh
  core/bash/tests/test_deploy_infrastructure.sh
  core/python/main.py
  core/python/scripts/setup_splunk.sh
  core/python/splunk/__init__.py
  core/python/splunk/deployer.py
  core/python/splunk/node_manager.py
  core/python/splunk/tests/test_deployer.py
  core/python/splunk/tests/test_node_manager.py
  core/python/splunk/tests/test_utils/test_splunk_api.py
  core/python/splunk/tests/test_utils/test_yaml_loader.py
  core/python/splunk/utils/__init__.py
  core/python/splunk/utils/ec2_helper.py
  core/python/splunk/utils/ec2_manager.py
  core/python/splunk/utils/s3_backend.py
  core/python/splunk/utils/splunk_api.py
  core/python/splunk/utils/yaml_loader.py
  core/python/tests/test_deployer.py
  core/python/tests/test_node_manager.py
  core/python/tests/test_utils/test_s3_backend.py
  core/python/tests/test_utils/test_yaml_loader.py
  user_inputs/admin/cloud/aws/vpc_config.yaml
  user_inputs/splunk/department/sales/example_splunk.yaml
Labels: enhancement

#39 doc(splunk): Development
  README.md
Labels: documentation

#40 feat(splunk): upd requirements.txt
  requirements.txt
Labels: enhancement

#41 feat(splunk): upd test_deployer.py
  core/python/tests/test_deployer.py
Labels: enhancement

#42 merge master to deenupdate
  README.md
  core/python/tests/test_deployer.py
  requirements.txt
Labels: enhancement

#44 feat(splunk): remove init module creation
  core/python/splunk/__init__.py
  core/python/splunk/utils/__init__.py
Labels: enhancement

#46 feat(splunk): add codecov
  .github/workflows/python.yml
Labels: enhancement

#47 doc(splunk): link codecov badge
  README.md
Labels: documentation

#48 fix(splunk): add missing module init
  README.md
  core/python/__init__.py
  core/python/scripts/__init__.py
  core/python/splunk/__init__.py
  core/python/splunk/utils/__init__.py
Labels: bug

#49 doc(splunk): add MIT LICENSE
  LICENSE
Labels: documentation

#52 doc(splunk): upd project scope in README.md
  README.md
Labels: documentation

#53 feat(splunk): update SECURITY.md
  SECURITY.md
Labels: documentation

#54 feat(splunk): Update CODE_OF_CONDUCT.md email
  CODE_OF_CONDUCT.md
Labels: documentation

#55 doc(splunk): slack connect to README.md
  README.md
Labels: documentation

#56 doc(splunk): Update README.md on slack badge
  README.md
Labels: documentation

#58 feat(splunk): update splunk_api.py
  core/python/splunk/utils/splunk_api.py
Labels: enhancement

#59 feat(splunk): merge main to deenupdate
  CODE_OF_CONDUCT.md
  README.md
  SECURITY.md
  core/python/splunk/utils/splunk_api.py
Labels: documentation

#60 feat(splunk): ec2 helper
  core/python/splunk/utils/ec2_helper.py
Labels: enhancement

#61 feat(splunk): Update s3_backend.py
  core/python/splunk/utils/s3_backend.py
Labels: enhancement

#62 feat(splunk): update ec2_manager.py
  core/python/splunk/utils/ec2_manager.py
Labels: documentation, enhancement

#63 feat(splunk): update ec2_manager.py
  core/python/splunk/utils/ec2_manager.py
Labels: enhancement

#64 feat(splunk): Update node_manager.py
  core/python/splunk/node_manager.py
Labels: enhancement

#65 feat(splunk): Update deployer.py
  core/python/splunk/deployer.py
Labels: enhancement

#67 feat(splunk): Update setup_splunk.sh
  core/python/scripts/setup_splunk.sh
Labels: enhancement
